// protoc-gen-permissions generates the Go catalog for each proto enum whose
// values carry the (moonbase.v1.description) option: a plain []Entry of
// {Key, Description}, where Key is the value name with its enum prefix dropped,
// lower-cased, and its last underscore turned into a dot (PERMISSION_USER_READ
// -> "user.read"). The enum is the single source — auth.Catalog aliases this
// generated slice — so adding a value with a description is all it takes; a
// value without one (UNSPECIFIED, the ALL wildcard) is not a catalog entry.
//
// The description option is read straight off the descriptor by field number,
// so this plugin never imports the generated options.pb.go — that would be a
// bootstrap cycle (the plugin runs inside the same buf invocation that
// generates it).
package main

import (
	"path"
	"strconv"
	"strings"
	"unicode"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/encoding/protowire"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/pluginpb"
)

// Field number of the moonbase.v1.description option (see proto/moonbase/v1/options.proto).
const optDescriptionEnumValue protowire.Number = 50001

// authcatalog is where the generated permission catalogs live; it is the
// single source of truth for grantable-permission key + description.
const catalogImportPath = "github.com/imbytecat/moonbase/server/internal/authcatalog"

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f)
		}
		return nil
	})
}

func generateFile(gen *protogen.Plugin, f *protogen.File) {
	var enums []*protogen.Enum
	for _, e := range f.Enums {
		if hasCatalogValues(e) {
			enums = append(enums, e)
		}
	}
	if len(enums) == 0 {
		return
	}

	base := strings.TrimSuffix(path.Base(f.Desc.Path()), ".proto")
	g := gen.NewGeneratedFile(base+".catalog.go", protogen.GoImportPath(catalogImportPath))
	g.P("// Code generated by protoc-gen-permissions. DO NOT EDIT.")
	g.P("// source: ", f.Desc.Path())
	g.P()
	g.P("package authcatalog")
	g.P()
	for _, e := range enums {
		genCatalog(g, e)
	}
}

// genCatalog emits the <Enum>Entry struct and the ordered <Enum>Catalog slice
// for one enum, one entry per value that carries a description.
func genCatalog(g *protogen.GeneratedFile, e *protogen.Enum) {
	name := e.GoIdent.GoName
	entryType := name + "Entry"
	catalogVar := name + "Catalog"

	g.P("type ", entryType, " struct {")
	g.P("\tKey         string")
	g.P("\tDescription string")
	g.P("}")
	g.P()
	g.P("var ", catalogVar, " = []", entryType, "{")
	prefix := screamingSnake(string(e.Desc.Name())) + "_"
	for _, v := range e.Values {
		desc, ok := stringOption(v.Desc.Options(), optDescriptionEnumValue)
		if !ok {
			continue
		}
		key := catalogKey(prefix, string(v.Desc.Name()))
		g.P("\t{Key: ", strconv.Quote(key), ", Description: ", strconv.Quote(desc), "},")
	}
	g.P("}")
	g.P()
}

// --- helpers -------------------------------------------------------------

func hasCatalogValues(e *protogen.Enum) bool {
	for _, v := range e.Values {
		if _, ok := stringOption(v.Desc.Options(), optDescriptionEnumValue); ok {
			return true
		}
	}
	return false
}

// catalogKey derives the wire/DB key from an enum value name: drop the enum
// prefix, lower-case, turn the last underscore into a dot. Mirrors the runtime
// permissionKey in internal/rpc so the generated keys match what the wire maps.
func catalogKey(prefix, valueName string) string {
	name := strings.ToLower(strings.TrimPrefix(valueName, prefix))
	if i := strings.LastIndex(name, "_"); i >= 0 {
		name = name[:i] + "." + name[i+1:]
	}
	return name
}

// screamingSnake converts a CamelCase enum name to the SCREAMING_SNAKE prefix
// protoc gives its values (Permission -> PERMISSION, PaymentMethod -> PAYMENT_METHOD).
func screamingSnake(s string) string {
	var b strings.Builder
	for i, r := range s {
		if i > 0 && unicode.IsUpper(r) && !unicode.IsUpper(rune(s[i-1])) {
			b.WriteByte('_')
		}
		b.WriteRune(unicode.ToUpper(r))
	}
	return b.String()
}

// stringOption reads a `string` extension with the given field number off an
// options message. It checks resolved extensions first (buf may link
// options.proto into the request) and falls back to the unknown-field bytes.
func stringOption(opts protoreflect.ProtoMessage, num protowire.Number) (string, bool) {
	if opts == nil {
		return "", false
	}
	msg := opts.ProtoReflect()
	var out string
	var found bool
	msg.Range(func(fd protoreflect.FieldDescriptor, v protoreflect.Value) bool {
		if fd.IsExtension() && fd.Number() == protoreflect.FieldNumber(num) &&
			fd.Kind() == protoreflect.StringKind {
			out = v.String()
			found = true
			return false
		}
		return true
	})
	if found {
		return out, true
	}
	return stringInUnknown(msg.GetUnknown(), num)
}

func stringInUnknown(b protoreflect.RawFields, num protowire.Number) (string, bool) {
	for len(b) > 0 {
		n, typ, taglen := protowire.ConsumeTag(b)
		if taglen < 0 {
			return "", false
		}
		b = b[taglen:]
		if n == num && typ == protowire.BytesType {
			v, vlen := protowire.ConsumeBytes(b)
			if vlen < 0 {
				return "", false
			}
			return string(v), true
		}
		skip := protowire.ConsumeFieldValue(n, typ, b)
		if skip < 0 {
			return "", false
		}
		b = b[skip:]
	}
	return "", false
}
