// protoc-gen-paymentcatalog generates the payment method catalog from any proto
// enum whose values carry the (moonbase.v1.method_provider) option — currently
// payment.v1.PaymentMethod. Each value becomes a catalog entry: id is the value
// name with its enum prefix dropped and lower-cased (PAYMENT_METHOD_PAGE_PAY ->
// "page_pay"), plus the provider, credential kind, and per-order inputs its
// options declare. The enum is the single source, so the two ends can't drift.
//
// It emits Go or TypeScript depending on the `lang` plugin parameter (buf runs
// it twice, once per language, into different out dirs):
//   - lang=go: internal/paymentcatalog, the []Method the pay drivers reference.
//   - lang=ts: the api-client gen tree, PROVIDER_METHODS + METHOD_INPUTS the
//     frontend re-exports (label/desc text stays in the web Chinese copy catalog).
//
// Options are read straight off the descriptor by field number, so this plugin
// never imports the generated options.pb.go — that would be a bootstrap cycle,
// exactly as protoc-gen-permissions does.
package main

import (
	"path"
	"strconv"
	"strings"
	"unicode"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/encoding/protowire"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/pluginpb"
)

// Field numbers of the moonbase.v1 method options (see proto/moonbase/v1/options.proto).
const (
	optMethodProvider       protowire.Number = 50002
	optMethodCredentialKind protowire.Number = 50003
	optMethodInput          protowire.Number = 50004
)

const paymentcatalogImportPath = "github.com/imbytecat/moonbase/server/internal/paymentcatalog"

type method struct {
	id       string
	provider string
	kind     string
	inputs   []string
}

func main() {
	var lang string
	opts := protogen.Options{}
	opts.ParamFunc = func(name, value string) error {
		if name == "lang" {
			lang = value
		}
		return nil
	}
	opts.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f, lang)
		}
		return nil
	})
}

func generateFile(gen *protogen.Plugin, f *protogen.File, lang string) {
	var methods []method
	for _, e := range f.Enums {
		methods = append(methods, methodsOf(e)...)
	}
	if len(methods) == 0 {
		return
	}
	base := strings.TrimSuffix(path.Base(f.Desc.Path()), ".proto")
	if lang == "ts" {
		genTS(gen, f, base, methods)
		return
	}
	genGo(gen, f, base, methods)
}

func methodsOf(e *protogen.Enum) []method {
	prefix := screamingSnake(string(e.Desc.Name())) + "_"
	var out []method
	for _, v := range e.Values {
		provider, ok := stringOption(v.Desc.Options(), optMethodProvider)
		if !ok {
			continue
		}
		kind, _ := stringOption(v.Desc.Options(), optMethodCredentialKind)
		id := strings.ToLower(strings.TrimPrefix(string(v.Desc.Name()), prefix))
		out = append(out, method{
			id:       id,
			provider: provider,
			kind:     kind,
			inputs:   repeatedStringOption(v.Desc.Options(), optMethodInput),
		})
	}
	return out
}

func genGo(gen *protogen.Plugin, f *protogen.File, base string, methods []method) {
	g := gen.NewGeneratedFile(base+".catalog.go", protogen.GoImportPath(paymentcatalogImportPath))
	g.P("// Code generated by protoc-gen-paymentcatalog. DO NOT EDIT.")
	g.P("// source: ", f.Desc.Path())
	g.P()
	g.P("package paymentcatalog")
	g.P()
	g.P("type Method struct {")
	g.P("\tID       string")
	g.P("\tProvider string")
	g.P("\tKind     string")
	g.P("\tInputs   []string")
	g.P("}")
	g.P()
	g.P("var Methods = []Method{")
	for _, m := range methods {
		g.P("\t{ID: ", strconv.Quote(m.id), ", Provider: ", strconv.Quote(m.provider),
			", Kind: ", strconv.Quote(m.kind), ", Inputs: ", goStringSlice(m.inputs), "},")
	}
	g.P("}")
	g.P()
}

func genTS(gen *protogen.Plugin, f *protogen.File, base string, methods []method) {
	name := path.Join(path.Dir(f.Desc.Path()), base+"_catalog_pb.ts")
	g := gen.NewGeneratedFile(name, "")
	g.P("// Code generated by protoc-gen-paymentcatalog. DO NOT EDIT.")
	g.P("// source: ", f.Desc.Path())
	g.P()
	g.P("export const PROVIDER_METHODS: Record<string, string[]> = {")
	for _, provider := range providersInOrder(methods) {
		g.P("  ", tsString(provider), ": ", tsStringArray(idsForProvider(methods, provider)), ",")
	}
	g.P("}")
	g.P()
	g.P("export const METHOD_INPUTS: Record<string, string[]> = {")
	for _, m := range methods {
		g.P("  ", tsString(m.id), ": ", tsStringArray(m.inputs), ",")
	}
	g.P("}")
	g.P()
}

// --- helpers -------------------------------------------------------------

func providersInOrder(methods []method) []string {
	seen := map[string]bool{}
	var out []string
	for _, m := range methods {
		if !seen[m.provider] {
			seen[m.provider] = true
			out = append(out, m.provider)
		}
	}
	return out
}

func idsForProvider(methods []method, provider string) []string {
	var out []string
	for _, m := range methods {
		if m.provider == provider {
			out = append(out, m.id)
		}
	}
	return out
}

func goStringSlice(ss []string) string {
	if len(ss) == 0 {
		return "nil"
	}
	var b strings.Builder
	b.WriteString("[]string{")
	for i, s := range ss {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(strconv.Quote(s))
	}
	b.WriteString("}")
	return b.String()
}

func tsString(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "'", "\\'")
	return "'" + s + "'"
}

func tsStringArray(ss []string) string {
	var b strings.Builder
	b.WriteString("[")
	for i, s := range ss {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(tsString(s))
	}
	b.WriteString("]")
	return b.String()
}

func screamingSnake(s string) string {
	var b strings.Builder
	for i, r := range s {
		if i > 0 && unicode.IsUpper(r) && !unicode.IsUpper(rune(s[i-1])) {
			b.WriteByte('_')
		}
		b.WriteRune(unicode.ToUpper(r))
	}
	return b.String()
}

// stringOption reads a `string` extension with the given field number off an
// options message, resolved extension first then the unknown-field bytes.
func stringOption(opts protoreflect.ProtoMessage, num protowire.Number) (string, bool) {
	if opts == nil {
		return "", false
	}
	msg := opts.ProtoReflect()
	var out string
	var found bool
	msg.Range(func(fd protoreflect.FieldDescriptor, v protoreflect.Value) bool {
		if fd.IsExtension() && fd.Number() == protoreflect.FieldNumber(num) && fd.Kind() == protoreflect.StringKind && !fd.IsList() {
			out = v.String()
			found = true
			return false
		}
		return true
	})
	if found {
		return out, true
	}
	return stringInUnknown(msg.GetUnknown(), num)
}

func stringInUnknown(b protoreflect.RawFields, num protowire.Number) (string, bool) {
	for len(b) > 0 {
		n, typ, taglen := protowire.ConsumeTag(b)
		if taglen < 0 {
			return "", false
		}
		b = b[taglen:]
		if n == num && typ == protowire.BytesType {
			v, vlen := protowire.ConsumeBytes(b)
			if vlen < 0 {
				return "", false
			}
			return string(v), true
		}
		skip := protowire.ConsumeFieldValue(n, typ, b)
		if skip < 0 {
			return "", false
		}
		b = b[skip:]
	}
	return "", false
}

// repeatedStringOption reads a `repeated string` extension: resolved list first,
// then every (num, bytes) entry in the unknown-field bytes.
func repeatedStringOption(opts protoreflect.ProtoMessage, num protowire.Number) []string {
	if opts == nil {
		return nil
	}
	msg := opts.ProtoReflect()
	var out []string
	msg.Range(func(fd protoreflect.FieldDescriptor, v protoreflect.Value) bool {
		if fd.IsExtension() && fd.Number() == protoreflect.FieldNumber(num) && fd.IsList() && fd.Kind() == protoreflect.StringKind {
			list := v.List()
			for i := range list.Len() {
				out = append(out, list.Get(i).String())
			}
			return false
		}
		return true
	})
	if len(out) > 0 {
		return out
	}
	return repeatedStringInUnknown(msg.GetUnknown(), num)
}

func repeatedStringInUnknown(b protoreflect.RawFields, num protowire.Number) []string {
	var out []string
	for len(b) > 0 {
		n, typ, taglen := protowire.ConsumeTag(b)
		if taglen < 0 {
			return out
		}
		b = b[taglen:]
		if n == num && typ == protowire.BytesType {
			v, vlen := protowire.ConsumeBytes(b)
			if vlen < 0 {
				return out
			}
			out = append(out, string(v))
			b = b[vlen:]
			continue
		}
		skip := protowire.ConsumeFieldValue(n, typ, b)
		if skip < 0 {
			return out
		}
		b = b[skip:]
	}
	return out
}
