// protoc-gen-settings generates the storage-side representation of each proto
// message marked (moonbase.v1.profile): a plain Go struct (with the wire-only
// <field>_set flags dropped) plus a codec that maps the message to and from
// that struct. The codec concentrates the write-only-secret rule in one
// generated place — Mask blanks secret values out of responses and sets the
// sibling <field>_set flag, FromProto reads them back, and Merge keeps a
// stored secret when an update carries an empty value (and keeps an immutable
// field's stored value outright).
//
// The custom options are read straight off the descriptor by field number, so
// this plugin never imports the generated options.pb.go — that would be a
// bootstrap cycle (the plugin runs inside the same buf invocation that
// generates it).
package main

import (
	"path"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/encoding/protowire"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/pluginpb"
)

// Field numbers of the moonbase.v1 custom options (see proto/moonbase/v1/options.proto).
const (
	optProfileMessage protowire.Number = 50001 // (moonbase.v1.profile) on MessageOptions
	optSecretField    protowire.Number = 50001 // (moonbase.v1.secret) on FieldOptions
	optImmutableField protowire.Number = 50002 // (moonbase.v1.immutable) on FieldOptions
)

// systemcodec is where the generated storage structs + codecs live; it is the
// single source of truth for channel profile shapes.
const systemcodecImportPath = "github.com/imbytecat/moonbase/server/internal/systemcodec"

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f)
		}
		return nil
	})
}

func generateFile(gen *protogen.Plugin, f *protogen.File) {
	profiles := profileMessages(f.Messages)
	if len(profiles) == 0 {
		return
	}

	// Every message the codec touches: each profile plus its nested config
	// messages, deduped, in a stable order (profiles first, then nested in
	// field order) so the output is deterministic.
	seen := map[protoreflect.FullName]bool{}
	var order []*protogen.Message
	var collect func(m *protogen.Message)
	collect = func(m *protogen.Message) {
		if seen[m.Desc.FullName()] {
			return
		}
		seen[m.Desc.FullName()] = true
		order = append(order, m)
		for _, fld := range m.Fields {
			if fld.Message != nil {
				collect(fld.Message)
			}
		}
	}
	for _, p := range profiles {
		collect(p)
	}

	base := strings.TrimSuffix(path.Base(f.Desc.Path()), ".proto")
	g := gen.NewGeneratedFile(base+".settings.go", protogen.GoImportPath(systemcodecImportPath))
	g.P("// Code generated by protoc-gen-settings. DO NOT EDIT.")
	g.P("// source: ", f.Desc.Path())
	g.P()
	g.P("package systemcodec")
	g.P()

	isProfile := map[protoreflect.FullName]bool{}
	for _, p := range profiles {
		isProfile[p.Desc.FullName()] = true
	}

	for _, m := range order {
		genStruct(g, m)
		if isProfile[m.Desc.FullName()] {
			genProfileMethods(g, m)
			genCodec(g, m)
		} else {
			genNestedHelpers(g, m)
		}
	}
}

// genStruct emits the storage struct for a message: every field except the
// wire-only <field>_set flags, with JSON tags matching the proto json_name so
// the JSONB shape stays camelCase.
func genStruct(g *protogen.GeneratedFile, m *protogen.Message) {
	flags := flagFieldNames(m)
	g.P("type ", m.GoIdent.GoName, " struct {")
	for _, fld := range m.Fields {
		if flags[fld.Desc.Name()] {
			continue
		}
		g.P("\t", fld.GoName, " ", storageType(fld), " `json:\"", fld.Desc.JSONName(), "\"`")
	}
	g.P("}")
	g.P()
}

// genProfileMethods emits the settings.Profile[P] surface (ProfileID /
// ProviderName / WithID) from the message's id and provider fields.
func genProfileMethods(g *protogen.GeneratedFile, m *protogen.Message) {
	name := m.GoIdent.GoName
	idField := fieldByName(m, "id")
	providerField := fieldByName(m, "provider")
	g.P("func (p ", name, ") ProfileID() string { return p.", idField.GoName, " }")
	g.P("func (p ", name, ") ProviderName() string { return p.", providerField.GoName, " }")
	g.P("func (p ", name, ") WithID(id string) ", name, " {")
	g.P("\tp.", idField.GoName, " = id")
	g.P("\treturn p")
	g.P("}")
	g.P()
}

// genNestedHelpers emits the package-level mask/fromProto helpers for a nested
// config message (the profile codec calls these for message-typed fields).
func genNestedHelpers(g *protogen.GeneratedFile, m *protogen.Message) {
	protoType := g.QualifiedGoIdent(m.GoIdent)
	name := m.GoIdent.GoName
	// fromProto: proto -> storage (copies every stored field, secrets included).
	g.P("func ", fromProtoFunc(m), "(in *", protoType, ") ", name, " {")
	g.P("\tif in == nil {")
	g.P("\t\treturn ", name, "{}")
	g.P("\t}")
	g.P("\treturn ", name, "{")
	emitFromProtoFields(g, m)
	g.P("\t}")
	g.P("}")
	g.P()
	// mask: storage -> proto (blanks secret values, sets <field>_set flags).
	g.P("func ", maskFunc(m), "(v ", name, ") *", protoType, " {")
	g.P("\treturn &", protoType, "{")
	emitMaskFields(g, m)
	g.P("\t}")
	g.P("}")
	g.P()
}

// genCodec emits the profile's codec type + exported var, with FromProto /
// Mask / Merge.
func genCodec(g *protogen.GeneratedFile, m *protogen.Message) {
	protoType := g.QualifiedGoIdent(m.GoIdent)
	name := m.GoIdent.GoName
	base := strings.TrimSuffix(name, "Profile")
	codecType := lowerFirst(base) + "Codec"
	codecVar := base + "Codec"

	g.P("type ", codecType, " struct{}")
	g.P()
	g.P("// ", codecVar, " maps ", name, " to and from its wire message and owns the")
	g.P("// write-only-secret rule for this channel.")
	g.P("var ", codecVar, " = ", codecType, "{}")
	g.P()

	g.P("func (", codecType, ") FromProto(in *", protoType, ") ", name, " {")
	g.P("\tif in == nil {")
	g.P("\t\treturn ", name, "{}")
	g.P("\t}")
	g.P("\treturn ", name, "{")
	emitFromProtoFields(g, m)
	g.P("\t}")
	g.P("}")
	g.P()

	g.P("func (", codecType, ") Mask(v ", name, ") *", protoType, " {")
	g.P("\treturn &", protoType, "{")
	emitMaskFields(g, m)
	g.P("\t}")
	g.P("}")
	g.P()

	g.P("func (", codecType, ") Merge(updated, stored ", name, ") ", name, " {")
	emitMergeBody(g, m, "")
	g.P("\treturn updated")
	g.P("}")
	g.P()
}

// emitFromProtoFields writes the field assignments for a proto->storage
// conversion (every non-flag field; message fields recurse via helpers).
func emitFromProtoFields(g *protogen.GeneratedFile, m *protogen.Message) {
	flags := flagFieldNames(m)
	for _, fld := range m.Fields {
		if flags[fld.Desc.Name()] {
			continue
		}
		getter := "in.Get" + fld.GoName + "()"
		if fld.Message != nil {
			g.P("\t\t", fld.GoName, ": ", fromProtoFunc(fld.Message), "(", getter, "),")
			continue
		}
		g.P("\t\t", fld.GoName, ": ", getter, ",")
	}
}

// emitMaskFields writes the field assignments for a storage->proto conversion:
// non-secret fields copy through, message fields recurse, secret fields are
// left blank and their <field>_set flag is set from the stored value.
func emitMaskFields(g *protogen.GeneratedFile, m *protogen.Message) {
	for _, fld := range m.Fields {
		if isFlagField(m, fld) {
			// Handled alongside its secret sibling below.
			continue
		}
		if isSecret(fld) {
			// Secret value is masked out; announce whether one is stored.
			if flag := flagFor(m, fld); flag != nil {
				g.P("\t\t", flag.GoName, ": v.", fld.GoName, " != \"\",")
			}
			continue
		}
		if fld.Message != nil {
			g.P("\t\t", fld.GoName, ": ", maskFunc(fld.Message), "(v.", fld.GoName, "),")
			continue
		}
		g.P("\t\t", fld.GoName, ": v.", fld.GoName, ",")
	}
}

// emitMergeBody walks the message tree emitting the secret keep + immutable
// keep statements. prefix is the storage path to the current message
// (e.g. ".Smtp"), rooted at updated/stored.
func emitMergeBody(g *protogen.GeneratedFile, m *protogen.Message, prefix string) {
	for _, fld := range m.Fields {
		if isFlagField(m, fld) {
			continue
		}
		switch {
		case isSecret(fld):
			p := prefix + "." + fld.GoName
			g.P("\tif updated", p, " == \"\" {")
			g.P("\t\tupdated", p, " = stored", p)
			g.P("\t}")
		case isImmutable(fld):
			p := prefix + "." + fld.GoName
			g.P("\tupdated", p, " = stored", p)
		case fld.Message != nil:
			emitMergeBody(g, fld.Message, prefix+"."+fld.GoName)
		}
	}
}

// --- helpers -------------------------------------------------------------

func profileMessages(msgs []*protogen.Message) []*protogen.Message {
	var out []*protogen.Message
	for _, m := range msgs {
		if hasBoolOption(m.Desc.Options(), optProfileMessage) {
			out = append(out, m)
		}
	}
	return out
}

func storageType(fld *protogen.Field) string {
	elem := scalarStorageType(fld)
	if fld.Desc.IsList() {
		return "[]" + elem
	}
	return elem
}

func scalarStorageType(fld *protogen.Field) string {
	switch fld.Desc.Kind() {
	case protoreflect.BoolKind:
		return "bool"
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		return "int32"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return "int64"
	case protoreflect.MessageKind:
		// Nested config lives in the same package — unqualified name.
		return fld.Message.GoIdent.GoName
	default:
		return "string"
	}
}

// flagFieldNames returns the set of proto field names that are the <field>_set
// flag of a secret field in the same message (dropped from the storage struct).
func flagFieldNames(m *protogen.Message) map[protoreflect.Name]bool {
	out := map[protoreflect.Name]bool{}
	for _, fld := range m.Fields {
		if !isSecret(fld) {
			continue
		}
		if flag := flagFor(m, fld); flag != nil {
			out[flag.Desc.Name()] = true
		}
	}
	return out
}

func isFlagField(m *protogen.Message, fld *protogen.Field) bool {
	return flagFieldNames(m)[fld.Desc.Name()]
}

// flagFor finds the <secret>_set bool sibling of a secret field.
func flagFor(m *protogen.Message, secret *protogen.Field) *protogen.Field {
	want := string(secret.Desc.Name()) + "_set"
	return fieldByName(m, want)
}

func fieldByName(m *protogen.Message, name string) *protogen.Field {
	for _, fld := range m.Fields {
		if string(fld.Desc.Name()) == name {
			return fld
		}
	}
	return nil
}

func isSecret(fld *protogen.Field) bool { return hasBoolOption(fld.Desc.Options(), optSecretField) }
func isImmutable(fld *protogen.Field) bool {
	return hasBoolOption(fld.Desc.Options(), optImmutableField)
}

func fromProtoFunc(m *protogen.Message) string { return lowerFirst(m.GoIdent.GoName) + "FromProto" }
func maskFunc(m *protogen.Message) string      { return "mask" + m.GoIdent.GoName }

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

// hasBoolOption reports whether the options message carries a `true` bool
// option with the given field number. It checks resolved extensions first
// (buf may link options.proto into the request) and falls back to parsing the
// unknown-field bytes (when the extension is not linked into this plugin).
func hasBoolOption(opts protoreflect.ProtoMessage, num protowire.Number) bool {
	if opts == nil {
		return false
	}
	msg := opts.ProtoReflect()
	found := false
	msg.Range(func(fd protoreflect.FieldDescriptor, v protoreflect.Value) bool {
		if fd.IsExtension() && fd.Number() == protoreflect.FieldNumber(num) && fd.Kind() == protoreflect.BoolKind {
			found = v.Bool()
			return false
		}
		return true
	})
	if found {
		return true
	}
	return boolInUnknown(msg.GetUnknown(), num)
}

func boolInUnknown(b protoreflect.RawFields, num protowire.Number) bool {
	for len(b) > 0 {
		n, typ, taglen := protowire.ConsumeTag(b)
		if taglen < 0 {
			return false
		}
		b = b[taglen:]
		if n == num && typ == protowire.VarintType {
			v, vlen := protowire.ConsumeVarint(b)
			if vlen < 0 {
				return false
			}
			return v != 0
		}
		skip := protowire.ConsumeFieldValue(n, typ, b)
		if skip < 0 {
			return false
		}
		b = b[skip:]
	}
	return false
}
